yumi:
  hiqp_joint_velocity_controller:
    #####      JOINT LIMITATIONS    #####
     hiqp_preload_jnt_limits:
      - link_frame: yumi_link_1_r
        limitations: [1.4835, -2.94, 2.94] #dq_max, lower joint limit, upper joint limit
      - link_frame: yumi_link_2_r
        limitations: [1.4835, -2.5, 0.75] 
      - link_frame: yumi_link_3_r
        limitations: [1.7453, -2.94, 2.94]
      - link_frame: yumi_link_4_r
        limitations: [1.3090, -2.16, 1.4]
      - link_frame: yumi_link_5_r
        limitations: [2.2689, -5.07, 5.07] 
      - link_frame: yumi_link_6_r
        limitations: [2.2689, -1.54, 2.41]
      - link_frame: yumi_link_7_r
        limitations: [2.2689, -4.0, 4.0] 

    ######      OBSTACLE AVOIDANCE PRIMITIVES    #####
     hiqp_preload_geometric_primitives:
      - name: floor_avoidance_plane
        type: plane 
        frame_id: yumi_body
        visible: true
        color: [0.5, 0.5, 0.5, 1.0]
        parameters: [0.0, 0.0, 1.0, 0.02]
      - name: yumi_link_5_r_avoidance_sphere
        type: sphere 
        frame_id: yumi_link_5_r
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [-0.023, -0.04, 0.1, 0.04]
      - name: yumi_link_6_r_avoidance_sphere
        type: sphere 
        frame_id: yumi_link_6_r
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [0.01, -0.01, -0.01, 0.06]
      - name: yumi_link_5_l_avoidance_sphere
        type: sphere 
        frame_id: yumi_link_5_l
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [-0.023, -0.04, 0.1, 0.04]
      - name: yumi_link_6_l_avoidance_sphere
        type: sphere 
        frame_id: yumi_link_6_l
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [0.01, -0.01, -0.01, 0.06]
      - name: yumi_gripper_base_r_avoidance_sphere
        type: sphere 
        frame_id: gripper_r_base
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [0.0, 0.0, 0.04, 0.035]
      - name: yumi_gripper_base_l_avoidance_sphere
        type: sphere 
        frame_id: gripper_l_base
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [0.0, 0.0, 0.04, 0.035]
      - name: yumi_fingers_r_avoidance_sphere
        type: sphere 
        frame_id: gripper_r_base
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [0.0, 0.0, 0.105, 0.0375]
      - name: yumi_fingers_l_avoidance_sphere
        type: sphere 
        frame_id: gripper_l_base
        visible: true
        color: [1.0, 0.0, 0.0, 0.6]
        parameters: [0.0, 0.0, 0.105, 0.0375]

     hiqp_preload_tasks:
      #####      ARM AVOIDANCE TASKS    #####
      - name: yumi_link_5_l_5_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_5_l_avoidance_sphere > yumi_link_5_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_5_l_6_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_5_l_avoidance_sphere > yumi_link_6_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_5_l_g_r_avoidance
#        priority: 1
#        visible: true
#        active: true
#        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_5_l_avoidance_sphere > yumi_gripper_base_r_avoidance_sphere']
#        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_5_l_f_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_5_l_avoidance_sphere > yumi_fingers_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_6_l_5_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_6_l_avoidance_sphere > yumi_link_5_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_6_l_6_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_6_l_avoidance_sphere > yumi_link_6_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_6_l_g_r_avoidance
#        priority: 1
#        visible: true
#        active: true
#        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_6_l_avoidance_sphere > yumi_gripper_base_r_avoidance_sphere']
#        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_6_l_f_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_link_6_l_avoidance_sphere > yumi_fingers_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_g_l_5_r_avoidance
#        priority: 1
#        visible: true
#        active: true
#        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_gripper_base_l_avoidance_sphere > yumi_link_5_r_avoidance_sphere']
#        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_g_l_6_r_avoidance
#        priority: 1
#        visible: true
#        active: true
#        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_gripper_base_l_avoidance_sphere > yumi_link_6_r_avoidance_sphere']
#        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_g_l_g_r_avoidance
#        priority: 1
#        visible: true
#        active: true
#        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_gripper_base_l_avoidance_sphere > yumi_gripper_base_r_avoidance_sphere']
#        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_g_l_f_r_avoidance
#        priority: 1
#        visible: true
#        active: true
#        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_gripper_base_l_avoidance_sphere > yumi_fingers_r_avoidance_sphere']
#        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_f_l_5_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_fingers_l_avoidance_sphere > yumi_link_5_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_f_l_6_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_fingers_l_avoidance_sphere > yumi_link_6_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
#      - name: yumi_link_f_l_g_r_avoidance
#        priority: 1
#        visible: true
#        active: true
#        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_fingers_l_avoidance_sphere > yumi_gripper_base_r_avoidance_sphere']
#        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_f_l_f_r_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'sphere', 'yumi_fingers_l_avoidance_sphere > yumi_fingers_r_avoidance_sphere']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']

      #####      FLOOR AVOIDANCE TASKS    #####
      - name: yumi_link_5_l_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_link_5_l_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_6_l_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_link_6_l_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_5_r_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_link_5_r_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_link_6_r_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_link_6_r_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_g_l_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_gripper_base_l_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_g_r_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_gripper_base_r_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_f_l_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_fingers_l_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']
      - name: yumi_f_r_floor_avoidance
        priority: 1
        visible: true
        active: true
        def_params: ['TDefGeomProj', 'sphere', 'plane', 'yumi_fingers_r_avoidance_sphere > floor_avoidance_plane']
        dyn_params: ['TDynFirstOrderCubic', '100000.0']





